dist: xenial
language: python
sudo: enabled
services:
    - mysql
python:
    - "3.7.0"
env:
    global:
     - lutece_runtime_mode=travis
before_install:
    - mysql -u root -e "CREATE DATABASE IF NOT EXISTS test_db CHARACTER SET utf8;"
    - mysql -u root -e "CREATE USER 'test_user'@'localhost' IDENTIFIED BY 'lUtEcEtRaViSdB';"
    - mysql -u root -e "GRANT ALL PRIVILEGES ON test_db.* TO 'test_user'@'localhost';"
    - mysql -u root -e "FLUSH PRIVILEGES;"
    - cp Lutece/config.py.template Lutece/config.py
install:
    - pip install -r requirements/requirements.txt

script:
    - python manage.py makemigrations --noinput
    - python manage.py migrate --noinput
    - python manage.py test
