dist: xenial
language: python
sudo: enabled
services:
    - mysql
python:
    - "3.7.0"
env:
    global:
     - lutece_runtime_mode=travis
before_install:
    - declare -a lutece_install_apps=("user"  "problem"  "judge"  "submission"  "data"  "article"  "record")
    - mysql -u root -e "CREATE DATABASE IF NOT EXISTS runtime_test_db CHARACTER SET utf8 COLLATE utf8_general_ci;"
    - mysql -u root -e "CREATE USER 'test_user'@'localhost' IDENTIFIED BY 'lUtEcEtRaViSdB';"
    - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'test_user'@'localhost';"
    - mysql -u root -e "FLUSH PRIVILEGES;"
    - cp Lutece/config.py.template Lutece/config.py
install:
    - pip install -r requirements/requirements.txt

script:
    # Database migrations / migrate test
    - for each in "${lutece_install_apps[@]}"; do python manage.py makemigrations $each ; echo run python manage.py makemigrations $each ; done
    - python manage.py migrate
    # Unit test
    - python manage.py test --noinput
    # Coverage test
    - function join { local IFS="$1"; shift; echo "$*"; }
    - source=join , ${lutece_install_apps[@]}
    - coverage run --source=$resource manage.py test --noinput

after_success:
    - coveralls