language: python
sudo: enabled
services:
    - mysql
python:
    - "3.7.0"
env:
    global:
     - lutece_runtime_mode=travis
before_install:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS test_db CHARACTER SET utf8'
    - mysql -e 'CREATE USER "test_user@localhost" IDENTIFIED BY "lUtEcEtRaViSdB"'
    - mv Lutece/config.py.template Lutece/config.py
install:
    - pip install -r requirements.txt

script:
    python manage.py makemigartions --noinput
    python manage.py migrate --noinput
    python manage.py test
